### ISSUE TITLE
把你的 oneinstack nginx配置文件 放出来看看.我用的oneinstack 怎么一直500错误.

### ISSUE THREAD

**Issue by ipme** [WangNingkai/OLAINDEX-CMD#1]
文件夹 权限也加了,,  
chmod 777 storage/app/config.json
配置文件 也777 了.  
我用的是你的自动安装脚本的.  

放一个完整的 nginx 规则  要是带SSL 就更好了!!!

**Comment by WangNingkai** [comment]
500错误看一下报错日志，位置storage/logs/*.log
